name: Build and Push Docker Image

on:
  push:
    branches:
      - main
    paths:
      - 'base/**'
      - 'opt/**'
      - 'usr/**'
      - '.github/workflows/**'
  workflow_dispatch:

jobs:
  build-push:
    name: Build and Push Voice-LLM Stack
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: base/Dockerfile
          push: true
          tags: |
            schnicklbob/quickpod-voice-llm:latest
            schnicklbob/quickpod-voice-llm:${{ github.sha }}
          platforms: linux/amd64
          cache-from: type=gha
          cache-to: type=gha,mode=max

      - name: Image digest
        run: echo Image pushed with tags latest and ${{ github.sha }}
